# cert manager first
# kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.16.2/cert-manager.yaml

# otel operator
helm repo add open-telemetry https://open-telemetry.github.io/opentelemetry-helm-charts
helm repo update

helm install -n hms-dev opentelemetry-operator open-telemetry/opentelemetry-operator \
--set manager.extraArgs={"--enable-go-instrumentation=true"} \
--set "manager.collectorImage.repository=otel/opentelemetry-collector-k8s"

-f ~/Downloads/values-opentelemetry-operator.yaml \

helm install -n hms-dev opentelemetry-operator open-telemetry/opentelemetry-operator \
--set "manager.collectorImage.repository=otel/opentelemetry-collector-k8s" \
--set "manager.featureGatesMap.operator.sidecarcontainers.native=true" \
--set "manager.featureGatesMap.operator.golang.flags=true"

helm install -n hms-dev opentelemetry-operator open-telemetry/opentelemetry-operator \
-f ~/Downloads/values-opentelemetry-operator.yaml \
--set "manager.collectorImage.repository=otel/opentelemetry-collector-k8s"

helm install -n hms-dev opentelemetry-operator open-telemetry/opentelemetry-operator \
--set "manager.featureGates=nativeSideCarContainers=true,golangFlags=true" \
--set "manager.collectorImage.repository=otel/opentelemetry-collector-k8s"



helm install -n hms-dev opentelemetry-operator open-telemetry/opentelemetry-operator \
-f ~/Downloads/values-opentelemetry-operator.yaml \
--set manager.collectorImage.repository=otel/opentelemetry-collector-k8s